name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: Commit index
      run: |
        git config --global user.name 'M1TE5H'
        git config --global user.email 'M1TE5H@users.noreply.github.com'
        git commit -am "index.html"
        git push
